name: GitHub Actions Build and Deploy Demo
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - run: bash _sidebar.sh
    - name: Checkout
      uses: actions/checkout@master

    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@master
      env:
        # ACCESS_TOKEN: ${{ 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 }}
        BRANCH: gh-pages
        FOLDER: build
        # BUILD_SCRIPT: npm install && npm run build