name: GitHub Actions Build and Deploy Demo
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # - run: pwd
    # - run: ls -la
    # - run: bash _sidebar.sh
    - run: bash deploy.sh
    - name: Checkout
      uses: actions/checkout@master
    - name: Sync to Gitee
      uses: wearerequired/git-mirror-action@master
      env:
        SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
      with:
        source-repo: git@github.com:ExcaliburEX/LifeBook.git
        destination-repo: git@gitee.com:ExcaliburAias/LifeBook.git
    - name: Build Gitee Pages
      uses: yanglbme/gitee-pages-action@main
      with:
          # 注意替换为你的 Gitee 用户名
          gitee-username: excaliburaias
          # 注意在 Settings->Secrets 配置 GITEE_PASSWORD
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          # 注意替换为你的 Gitee 仓库，仓库名严格区分大小写，请准确填写，否则会出错
          gitee-repo: ExcaliburAias/LifeBook
          # 要部署的分支，默认是 master，若是其他分支，则需要指定（指定的分支必须存在）
          branch: main

    # - name: Build and Deploy
    #   uses: JamesIves/github-pages-deploy-action@master
    #   env:
        # ACCESS_TOKEN: ${{ secrets.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 }}
        # BRANCH: gh-pages
        # FOLDER: build
        # BUILD_SCRIPT: npm install && npm run build