name: GitHub Actions Build and Deploy Demo
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # - run: pwd
    # - run: ls -la
    # - run: bash _sidebar.sh
    - run: npm i -g @cloudbase/cli
    - run: tcb login --apiKeyId AKIDUjnjR2sdTUGm6Bjcy47x1zlIchz1KKgu --apiKey AJFvMYWFm4T1KNCmfIfqoXO3YooY3C8C
    - run: tcb hosting deploy -e hello-cloudbase-5go3yssk369fd9e3
    - name: Checkout
      uses: actions/checkout@master

    # - name: Build and Deploy
    #   uses: JamesIves/github-pages-deploy-action@master
    #   env:
        # ACCESS_TOKEN: ${{ secrets.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 }}
        # BRANCH: gh-pages
        # FOLDER: build
        # BUILD_SCRIPT: npm install && npm run build